@startuml
start
while (输入正确的用户登录名和密码)
  :判断是否输入正确;
  :输入错误，登录失败;
endwhile
:输入正确，登录成功;
if (进入管理员主界面，查看个人信息) then
  fork
    :学生管理;
    :查看 / 删除 / 编辑 / 增加学生信息;
  fork again
    :教师管理;
    :查看 / 删除 / 编辑 / 增加教师信息;
    fork again
        :课程管理;
        :查看 / 删除 / 编辑 / 增加课程信息 & 排课;
        fork again
                :班级管理;
                :查看 / 删除 / 编辑 / 增加班级信息 & 查看指定班级学生信息;
  end fork

endif
:点击退出，退出当前账号;
stop

@enduml